# Generated by Django 6.0.6 on 2026-06-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=20)),
                ('rate_per_km', models.FloatField(default=12)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('pickup', models.TextField()),
                ('drop', models.TextField()),
                ('distance_km', models.FloatField(default=0)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('passengers', models.IntegerField(default=1)),
                ('luggage', models.IntegerField(default=0)),
                ('total_fare', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
