# Generated by Django 6.0.6 on 2026-06-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='car',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='luggage',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_fare',
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting For Driver'), ('accepted', 'Driver Accepted'), ('confirmed', 'Booking Confirmed'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
