# Generated by Django 6.0.6 on 2026-06-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_booking_car_booking_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='drivers/photos/')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('aadhar_photo', models.ImageField(blank=True, null=True, upload_to='drivers/aadhar/')),
                ('license_number', models.CharField(max_length=30)),
                ('license_photo', models.ImageField(upload_to='drivers/license/')),
            ],
        ),
    ]
