# Generated by Django 6.0.6 on 2026-06-17 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.driver'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='rejected_bookings', to='bookings.driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting For Driver'), ('confirmed', 'Booking Confirmed'), ('rejected', 'Rejected'), ('no_driver', 'No Driver Available'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
