# Generated by Django 6.0.5 on 2026-06-18 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_car_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='aadhar_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='driver_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='aadhar_photo',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_photo',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.car'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.driver'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for driver'), ('confirmed', 'Driver confirmed'), ('cancelled', 'Auto-cancelled'), ('rejected', 'Driver rejected'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rate_per_km',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
    ]
