# Generated by Django 6.1.1 on 2026-09-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=6),
        ),
        migrations.AddField(
            model_name='car',
            name='driver_allowance',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
        ),
        migrations.AddField(
            model_name='car',
            name='max_passengers',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='rate_per_km_pax2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional — per-km rate when 2 passengers are selected (e.g. for bikes). Leave blank to always charge rate_per_km regardless of passenger count.', max_digits=6, null=True),
        ),
    ]
